name: 'Base Setup'
description: 'Install necessary tooling and restore dependencies'
inputs:
  dotnet-version:
    description: 'Version of dotnet core SDK to install'
    required: false
    default: '3.x.1'
  nbgv-version:
    description: 'Version of NBGV to install'
    required: false
    default: 3.3.37
runs:
  using: "composite"
  steps:
    - name: Checkout files
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    - name: Setup NBGV
      uses: dotnet/nbgv@v0.4
      with:
        toolVersion: ${{ inputs.nbgv-version }}
    - name: Restore dependencies
      run: dotnet restore "${{ github.workspace }}/src/SDK.sln"