name: 'Build Solution'
description: 'Build the entire SDK solution'
inputs:
  dotnet-version:
    description: 'Version of dotnet core SDK to install'
    required: false
    default: '3.x.1'
  nbgv-version:
    description: 'Version of NBGV to install'
    required: false
    default: 3.3.37
runs:
  using: "composite"
  steps:
    - uses: '${{ github.workspace }}/.github/actions/base'
    - name: Build solution
      run: dotnet build "${{ github.workspace }}/src/SDK.sln" --no-restore -c Release